activity_log/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'(?P<category_pk>\d+)/(?P<activity_pk>\d+)/$', views.activity_detail, name='activity_detail'),
    url(r'^play_pause_click/$', views.play_pause_click, name='play_pause_click'),
    url(r'(?P<pk>\d+)/$', views.activity_list, name='activity_list'),
    url(r'^$', views.home, name='home'),
    # url(r'^register/$', views.register, name='register'),
]

django_sandbox/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^activity_log/', include('activity_log.urls', namespace='activity_log')),
    url(r'^caption_maker/', include('caption_maker.urls', namespace='caption_maker')),
    url(r'^admin/', admin.site.urls),
    url(r'^numbers_quiz$', views.numbers_quiz),
    url(r'nibuzhidaodeshi$', views.nibuzhidaodeshi),
    url(r'^login$', views.login_user),
    url(r'^logout$', views.logout_user),
    url(r'^registration/', views.registration),
    url(r'^$', views.home),
]

urlpatterns += staticfiles_urlpatterns()

activity_log/models.py
from __future__ import unicode_literals

from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User


class Category(models.Model):
    title = models.CharField(max_length=255)
    color = models.CharField(max_length=6)
    order = models.IntegerField(default=0)
    
    class Meta:
        ordering = ['order',]
    
    def __str__(self):
        return self.title


class Activity(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    link = models.CharField(max_length=255)
    
    class Meta:
        ordering = ['order',]
        
    def __str__(self):
        return self.title

        
class Log(models.Model):
    activity = models.ForeignKey(Activity)
    duration = models.IntegerField()
    created_at = models.DateTimeField(null=True, blank=True)
    comment = models.TextField(blank=True, default='')
    
    class Meta:
        ordering = ['-created_at',]
        
    def __str__(self):
        return self.comment

        
class LogTimer(models.Model):
    log = models.ForeignKey(Log)
    action = models.BooleanField() # 1=start/resume, 0=pause
    action_time = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-action_time',]


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    
    #Additional Fields
    bio = models.TextField(blank=True, default='')
    allow_edit = models.BooleanField(default=True)
    
    def __str__(self):
        return self.user.username
        
        
        
        
        
        

activity_log/views.py
from django.shortcuts import render, get_object_or_404 
from django.http import HttpResponse
from .models import Category, Activity, Log, LogTimer
from datetime import datetime


def home(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'activity_log/home.html', context)


def activity_list(request, pk):
    category = get_object_or_404(Category, pk=pk)
    context = {
        'category': category
    }
    return render(request,  'activity_log/activity_list.html', context)


def play_pause_click(request):
    
    if request.method == 'POST':
        data = request.GET
        activity_pk = data['activity_pk']
        activeLog = Log.objects.filter(activity_id=activity_pk, created_at__isnull=True)
        
        if activeLog:
            activeLog = activeLog[0]

        else:
            activeLog = Log(comment=data['comment'], duration=data['duration'], activity_id=activity_pk)
            activeLog.save()
        
        # create a LogTimer object to track play/pause clicks
        logTimerBool = data['play_pause'] # True=play, False=pause
        logTimer = LogTimer(log=activeLog, action=logTimerBool)
        logTimer.save()

    return HttpResponse(request)

def add_new_log(request):
    
    # if no active log is present, create new
    if activeLog is None:
        activeLog = Log(comment=data['comment'], duration=dur, activity=activity, created_at=datetime.now())
        activeLog.save()
    
    # else edit existing active log
    else:
        activeLog.comment = data['comment']
        activeLog.duration = dur
        activeLog.created_at = datetime.now()
        activeLog.save()
    
    logs = getLogs(activity_pk)

    context = {
        'activity': activity,
        'logs': logs,
    }
    
    return render(request, 'activity_log/activity_detail.html', context)
    

def activity_detail(request, category_pk, activity_pk):
    
    # Get all Log entries for given activity
    def getLogs(activity_pk):
        try:
            logs = Log.objects.filter(activity_id=activity_pk, created_at__isnull=False)
            
            # Change display of datetime variables
            for log in logs:
                log.created_at = log.created_at.strftime("%Y-%m-%d %H:%M")
                hours = log.duration // 60
                minutes = log.duration % 60
                log.duration = "%d:%02d" % (hours, minutes)
            
        except Log.DoesNotExist:
            logs = None
            
        return logs
    
    # Get activity from DB, Form object, and Log entries
    activity = get_object_or_404(Activity, category_id=category_pk, pk=activity_pk)
    logs = getLogs(activity_pk)
    
    # if form has been submitted
    if request.method == "POST":
        data = request.POST
        
        # for key in data:
        #     value = data[key]
        #     print("key: %s, value: %s" % (key,value))

        activeLog = Log.objects.filter(activity_id=activity_pk, created_at__isnull=True)
        
        hours = int(data['hour'])
        minutes = int(data['min'])
        seconds = int(data['sec'])
        
        if seconds >= 30:
            minutes = minutes + 1
        
        dur = hours * 60 + minutes
        
        # if no active log is present, create new
        if activeLog is None:
            activeLog = Log(comment=data['comment'], duration=dur, activity=activity, created_at=datetime.now())
            activeLog.save()
        
        # else edit existing active log
        else:
            activeLog.comment = data['comment']
            activeLog.duration = dur
            activeLog.created_at = datetime.now()
            activeLog.save()

        logs = getLogs(activity_pk)

    context = {
        'activity': activity,
        'logs': logs,
    }
    
    return render(request, 'activity_log/activity_detail.html', context)
    
    
    

activity_log/templates/activity_log/activity_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ activity.title }}{% endblock %}

{% block css %}
<link type="text/css" media="screen" href="{% static 'activity_log/css/stopwatch.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h2>{{ activity.title }} <small>{{ activity.category.title }}</small></h2>
    <p>{{ activity.description }}</p>
</div>

<input type="hidden" id="activity-id-hidden" name="activity-id" value="{{ activity.id }}">

<div class="row">
    <div class="col-md-3">
        <h2>Add New Entry:</h2>
        <form method="POST">{% csrf_token %}
            <textarea id="comment-textarea" name="comment" rows="3">Enter Comment Here...</textarea>
            
            <audio id="alarm">
                <source src="{% static 'activity_log/media/audio/metronome.mp3' %}" type="audio/mpeg">
            </audio>
            
            <div class="stopwatch">
                
                <b>Duration: </b>
                <input type="number" id="stopwatch_hr" class="stopwatch_number" name="hour" min="0" step="1"/> : 
                <input type="number" id="stopwatch_min" class="stopwatch_number" name="min" min="0" max="59" step="1"/> : 
                <input type="number" id="stopwatch_sec" class="stopwatch_number" name="sec" min="0" max="59" step = "1"/>
                
                <button type="button" name="play-pause" id='play_pause' class="btn btn-default btn-md" value="play">
                    <span class="glyphicon glyphicon-play"></span> Start
                </button>
                
            </div>
            <br/>
            <input type="submit" id="addLog-submit" class="btn btn-primary" name="addLog-submit" value="Add New Log">
        </form>
    </div>
    
    <div class="col-md-9">
        <h2>Activity Log:</h2>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <td>Created On</td>
                    <td>Duration</td>
                    <td>Comment</td>
                </tr>
            </thead>  
            
            {% for log in logs %}
            <tr>
                <td>{{ log.created_at }}</td>
                <td>{{ log.duration }}</td>
                <td>{{ log.comment }}</td>
            </tr>
            {% endfor %}
        </table>  
    </div>
</div>


{% endblock %}


{% block js-foot %}
<script src="{% static 'activity_log/js/stopwatch.js' %}"></script>
{% endblock %}
    

activity_log/templates/activity_log/activity_list.html
{% extends "base.html" %}

{% block title %}{{ category.title }}{% endblock %}

{% block content %}
<article>
    <h2>{{ category.title }}</h2>
    
    <section>
        {% for activity in category.activity_set.all %}
            <h3>
            <a href="{% url 'activity_log:activity_detail' category_pk=category.pk activity_pk=activity.pk %}">
                {{ activity.title }}
            </a>
            </h3>
            {{ activity.description }}
        {% endfor %}
    </section>
</article>
{% endblock %}

activity_log/templates/activity_log/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Well hello there!{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/countdown.css' %}">
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>Activity Log</h1>
    <p>Here's a placeholder landing page where a user will be able to see a graph of their activity logs, goals, and an evaluation of their performance.<p>
      <!--<a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">Don't Click Me &raquo;</a>-->
    </p>
</div>

<h2>Categories</h2>
<ul class="nav nav-pills nav-stacked">
    {% for category in categories %}
    <li role="presentation"><a class="text-center" href="{% url 'activity_log:activity_list' pk=category.pk %}">{{ category.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

{% block js-foot %}
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.0.min.js"></script>
<script src="{% static 'js/countdown.js' %}"></script>
{% endblock %}