activity_log/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'(?P<category_pk>\d+)/(?P<activity_pk>\d+)/$', views.activity_detail, name='activity_detail'),
    url(r'^play_pause_click/$', views.play_pause_click, name='play_pause_click'),
    url(r'(?P<pk>\d+)/$', views.activity_list, name='activity_list'),
    url(r'^$', views.home, name='home'),
    # url(r'^register/$', views.register, name='register'),
]

caption_maker/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'(?P<media_pk>\d+)/$', views.media_detail, name='media_detail'),
    url(r'^new$', views.create_new, name='create_new'),
    url(r'^modify/(?P<media_pk>\d+)$', views.modify_media, name='modify_media'),
    url(r'^submit_captions/$', views.submit_captions, name='submit_captions'),
    url(r'^favorite_media/$', views.favorite_media, name='favorite_media'),
    url(r'^media_list$', views.media_list, name='media_list'),
    # url(r'^login/$','django.contrib.auth.views.login', name='login',
    #     kwargs={'template_name': 'accounts/login.html'}),
    url(r'^login_register$', views.login_register, name='login_register'),
    url(r'^$', views.home, name='home'),
    # url(r'^register/$', views.register, name='register'),
]

django_sandbox/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^activity_log/', include('activity_log.urls', namespace='activity_log')),
    url(r'^caption_maker/', include('caption_maker.urls', namespace='caption_maker')),
    url(r'^admin/', admin.site.urls),
    url(r'^numbers_quiz$', views.numbers_quiz),
    url(r'nibuzhidaodeshi$', views.nibuzhidaodeshi),
    url(r'^login$', views.login_user),
    url(r'^logout$', views.logout_user),
    url(r'^registration/', views.registration),
    url(r'^$', views.home),
]

urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Sandbox site for programming in Django, jQuery, JavaScript">
  <meta name="author" content="Theodore Lano">
  <link rel="icon" href="{% static 'img/tl_favicon.png' %}">

  <title>{% block title %} Ted Tools {% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/social-buttons.css' %}" rel="stylesheet">
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-custom.css' %}" rel="stylesheet">
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
  <!--<link href="{% static 'css/custom-bootstrap.css' %}" rel="stylesheet">-->

  {% block css %}{% endblock %}

</head>

<body>
  <div class="container-fluid">
    {% include 'navbar.html' %}
  </div> <!-- /container -->
  
  <div class="container body">
    {% block content %}{% endblock %}
  </div>

  <footer class="text-center footer">
    <hr/>
    <div class="row footer">
      <div class="col-sm-3">
      </div>
      <div class="col-sm-6">
        <div class="footer-block">
          <a href="https://www.facebook.com/ted.lano" class="btn btn-facebook" target="_blank"><i class="fa fa-facebook"></i></a>
          <a href="https://twitter.com/tlano" class="btn btn-twitter" target="_blank"><i class="fa fa-twitter" target="_blank"></i></a>
          <a href="https://www.linkedin.com/in/theodore-lano-b5a34723" class="btn btn-linkedin" target="_blank"><i class="fa fa-linkedin"></i></a>
          <a href="https://www.instagram.com/tederoo/" class="btn btn-instagram" target="_blank"><i class="fa fa-instagram"></i></a>
          <a href="https://github.com/theodore4889" class="btn btn-github" target="_blank"><i class="fa fa-github"></i></a>
        </div>
      </div>
      <div class="col-sm-3">
      </div>
    </div>
  </footer>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.validate.min.js' %}"></script>
  <script src="{% static 'js/block-ui.js' %}"></script>
  <script src="{% static 'js/global.js' %}"></script>
  {% block js-foot %} {% endblock js-foot %}

</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home | {{ block.super }}{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/countdown.css' %}">
{% endblock %}

{% block content %}
<br/>
<div class="jumbotron">
<h1>Welcome to my playground</h1>
<p>Not much to see here.  You can do a few things, such as:</p>
<ul>
	<li>Check out my Youtube captioning app by clicking "Caption Maker" in the navigation.  Doesn't work well on iPhones.</li>
	<li>Practice your foreign language skills for numbers by clicking the "Numbers Quiz" in the navigation.</li>
	<li>There's also a countdown clock below, so thats something</li>
</ul>

</div>

<h3>Countdown to Mother's Day</h3>
<ul id="countdown">
	<li class="num_block">
		<div class="number days">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">DAYS</p>
	</li>
	<li class="num_block">
		<div class="number hours">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">HOURS</p>
	</li>
	<li class="num_block">
		<div class="number minutes">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">MINUTES</p>
	</li>
	<li class="num_block">
		<div class="number seconds">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">SECONDS</p>
	</li>
</ul>


{% endblock %}

{% block js-foot %}
<script src="{% static 'js/countdown.js' %}"></script>
{% endblock %}

templates/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-default">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'views.home' %}">
      <img alt="Brand" src="{% static 'img/tl_favicon.png' %}">
    </a>
    
    <a class="navbar-brand" href="{% url 'views.home' %}">Ted's Tools</a>
  </div>

  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar">
      <li><a href="{% url 'caption_maker:media_list' %}">Caption Maker</a></li>
      <li><a href="{% url 'views.numbers_quiz' %}">Numbers Quiz</a></li>
      <!-- <li><a href="{% url 'activity_log:home' %}">Activity Log</a></li> -->
    </ul>
    
    <div class="nav navbar-nav navbar-right">
      {% if not user.is_authenticated %}
      <form class="navbar-form navbar-left" role="login" method="POST" action="/login">{% csrf_token %}
        <div class="form-group login-input">
          <input type="text" id="login-username" name="username" class="form-control" placeholder="Username">
          <input type="password" id="login-password" name="password" class="form-control" placeholder="Password">
        </div>
        <button type="submit" id="login-button" class="btn btn-primary navbar-sm">Login</button>
      </form>
      <a href="{% url 'views.registration' %}">
        <button type="button" id="register-button" class="btn btn-default navbar-sm navbar-btn">Register</button>
      </a>
      {% else %}
      <p class="navbar-text hidden-xs">Welcome, {{ user.first_name }}!</p>
      <ul class="nav navbar-nav">
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          </a>
          <ul class="dropdown-menu">
            <li class="disabled"><a href="#">Settings</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="{% url 'views.logout_user' %}">Logout</a></li>
          </ul>
        </li>
      </ul>

      
      {% endif %}
      <span>&nbsp;</span>
    </div>
  </div><!--/.nav-collapse -->
  
</nav>

templates/nibuzhidaodeshi.html
{% extends "base.html" %}
{% load static %}

{% block title %}Learn Chinese Songs!{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/chinese.css' %}">
{% endblock %}

{% block content %}

<div class="text-center row">
    <div class=".col-md-12">
    
        <div id="player" class="video"></div>
        
        <!--<iframe width="560" height="315" -->
        <!--        src="https://www.youtube.com/embed/oHdS2Vfo0vM" frameborder="0">-->
        <!--</iframe>-->
        <br/>
    	<div id="pinyin-toggle" class="btn-group">
        	<button id="py-show" class="py-toggle btn btn-primary btn-sm active">Show Pinyin</button>
        	<button id="py-hide" class="py-toggle btn btn-primary btn-sm">Hide Pinyin</button>
    	</div>
    		
        <br/><br/>
        
        <div class="lyrics-container center">
            <table class="lyrics center">
                <tbody>
                    <tr id="cn-1" class="hanzi"><td>蝴蝶眨几次眼睛</td></tr>
                    <tr id="py-1" class="pinyin"><td>Húdié zhǎ jǐ cì yǎnjīng</td></tr>
                    <tr id="cn-2" class="hanzi"><td>才学会飞行</td></tr>
                    <tr id="py-2" class="pinyin"><td>cái xuéhuì fēixíng</td></tr>
                    <tr id="cn-3" class="hanzi"><td>夜空洒满了星星</td></tr>
                    <tr id="py-3" class="pinyin"><td>yèkōng sǎ mǎnle xīngxīng</td></tr>
                    <tr id="cn-4" class="hanzi"><td>但几颗会落地</td></tr>
                    <tr id="py-4" class="pinyin"><td>dàn jǐ kē huì luòdì</td></tr>
                    <tr><td> &nbsp; </td></tr>
                    <tr id="cn-5" class="hanzi"><td>我飞行 但你坠落之际</td></tr>
                    <tr id="py-5" class="pinyin"><td>wǒ fēixíng dàn nǐ zhuìluò zhī jì</td></tr>
                    <tr id="cn-6" class="hanzi"><td>很靠近 还听见呼吸</td></tr>
                    <tr id="py-6" class="pinyin"><td>hěn kàojìn hái tīngjiàn hūxī</td></tr>
                    <tr id="cn-7" class="hanzi"><td>对不起 我却没捉紧你</td></tr>
                    <tr id="py-7" class="pinyin"><td>duìbùqǐ wǒ què méi zhuō jǐn nǐ</td></tr>
                    <tr><td> &nbsp; </td></tr>
                    <tr id="cn-8" class="hanzi"><td>你不知道我为什么离开你</td></tr>
                    <tr id="py-8" class="pinyin"><td>nǐ bù zhīdào wǒ wèishéme líkāi nǐ</td></tr>
                    <tr id="cn-9" class="hanzi"><td>我坚持不能说放任你哭泣</td></tr>
                    <tr id="py-9" class="pinyin"><td>wǒ jiānchí bùnéng shuō fàngrèn nǐ kūqì</td></tr>
                    <tr id="cn-10" class="hanzi"><td>你的泪滴像 倾盆大雨 碎了满地</td></tr>
                    <tr id="py-10" class="pinyin"><td>nǐ de lèi dī xiàng qīngpén dàyǔ suìle mǎn dì</td></tr>
                    <tr id="cn-11" class="hanzi"><td>在心里清晰</td></tr>
                    <tr id="py-11" class="pinyin"><td>zài xīnlǐ qīngxī</td></tr>
                    <tr><td> &nbsp; </td></tr>
                    <tr id="cn-12" class="hanzi"><td>你不知道我为什么狠下心</td></tr>
                    <tr id="py-12" class="pinyin"><td>nǐ bù zhīdào wǒ wèishéme hěn xiàxīn</td></tr>
                    <tr id="cn-13" class="hanzi"><td>盘旋在你看不见的高空里</td></tr>
                    <tr id="py-13" class="pinyin"><td>pánxuán zài nǐ kàn bùjiàn de gāokōng lǐ</td></tr>
                    <tr id="cn-14" class="hanzi"><td>多的是 你不知道的事</td></tr>
                    <tr id="py-14" class="pinyin"><td>duō de shì nǐ bù zhīdào de shì</td></tr>
                    <tr><td> &nbsp; </td></tr>
                    <tr id="cn-15" class="hanzi"><td>我飞行 但你坠落之际</td></tr>
                    <tr id="py-15" class="pinyin"><td>wǒ fēixíng dàn nǐ zhuìluò zhī jì</td></tr>
                    <tr id="cn-16" class="hanzi"><td>你不知道我为什么离开你</td></tr>
                    <tr id="py-16" class="pinyin"><td>nǐ bù zhīdào wǒ wèishéme líkāi nǐ</td></tr>
                    <tr id="cn-17" class="hanzi"><td>我坚持不能说放任你哭泣</td></tr>
                    <tr id="py-17" class="pinyin"><td>wǒ jiānchí bùnéng shuō fàngrèn nǐ kūqì</td></tr>
                    <tr id="cn-18" class="hanzi"><td>你的泪滴像 倾盆大雨 碎了满地</td></tr>
                    <tr id="py-18" class="pinyin"><td>nǐ de lèi dī xiàng qīngpén dàyǔ suìle mǎn dì</td></tr>
                    <tr id="cn-19" class="hanzi"><td>在心里清晰</td></tr>
                    <tr id="py-19" class="pinyin"><td>zài xīnlǐ qīngxī</td></tr>
                    <tr><td> &nbsp; </td></tr>
                    <tr id="cn-20" class="hanzi"><td>你不知道我为什么狠下心</td></tr>
                    <tr id="py-20" class="pinyin"><td>nǐ bù zhīdào wǒ wèishéme hěn xiàxīn</td></tr>
                    <tr id="cn-21" class="hanzi"><td>盘旋在你看不见的高空里</td></tr>
                    <tr id="py-21" class="pinyin"><td>pánxuán zài nǐ kàn bùjiàn de gāokōng lǐ</td></tr>
                    <tr id="cn-22" class="hanzi"><td>多的是 你不知道的事</td></tr>
                    <tr id="py-22" class="pinyin"><td>duō de shì nǐ bù zhīdào de shì</td></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block js-foot %}
<script src="{% static 'js/nibuzhidaodeshi.js' %}"></script>
{% endblock %}

templates/numbers_quiz.html
{% extends "base.html" %}
{% load static %}

{% block title %}Numbers Quiz{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/chineseNumbers.css' %}">
{% endblock %}

{% block content %}

<div class="number-quiz">
	
	<h2>Numbers Quiz!</h2>
	<p>Select language, click speaker icon to listen, and guess number</p>

	<audio id="num-audio" type="audio/mpeg"></audio>
	<button type="button" id="sound-button" class="btn btn-primary sound-button" 
		data-toggle="tooltip" data-placement="left" title="Play Sound">
		<span class="glyphicon glyphicon-volume-up" aria-hidden="true"></span>
	</button>
	&nbsp;
	<button type="button" id="answer-button" class="btn btn-danger answer-button"
		data-toggle="tooltip" data-placement="right" title="Show Answer">
		<b>?</b>
	</button>
	<br/><br/>
	<input type="number" id="guess-input" name="guess"/>
	<p id='results-text'>Correct: 0, Wrong: 0, Streak: 0</p>
	
	<div id='number-entry-pad'>
		<div class="number-row">
			<button id="num-1" class="number">1</button>
			<button id="num-2" class="number">2</button>
			<button id="num-3" class="number">3</button>
		</div>
		
		<div class="number-row">
			<button id="num-4" class="number">4</button>
			<button id="num-5" class="number">5</button>
			<button id="num-6" class="number">6</button>
		</div>
		
		<div class="number-row">
			<button id="num-7" class="number">7</button>
			<button id="num-8" class="number">8</button>
			<button id="num-9" class="number">9</button>
		</div>
		
		<div class="number-row">
			<button id="num-rem" class="number btn-danger">
				<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
			</button>
			<button id="num-0" class="number">0</button>
			<button id="num-ok" class="number btn-success">
				<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
			</button>
		</div>
	</div>
	<br/>

	<div class="settings">
		<p><b>Number of Digits</b></p>
		<div id="digit-buttons" class="btn-group">
			<button id="dig-1" class="digit btn btn-primary btn-sm">1</button>
			<button id="dig-2" class="digit btn btn-primary btn-sm">2</button>
			<button id="dig-3" class="digit btn btn-primary btn-sm active">3</button>
			<button id="dig-4" class="digit btn btn-primary btn-sm">4</button>
			<button id="dig-5" class="digit btn btn-primary btn-sm">5</button>
			<button id="dig-6" class="digit btn btn-primary btn-sm">6</button>
			<button id="dig-7" class="digit btn btn-primary btn-sm">7</button>
			<button id="dig-8" class="digit btn btn-primary btn-sm">8</button>
			<button id="dig-9" class="digit btn btn-primary btn-sm">9</button>
		</div>
		<br/><br/>
	
		<p><b>Toggle Number Display</b></p>
		<div id="label-toggle" class="btn-group">
	    	<button id="num-std" class="options-numDisplay btn btn-primary btn-sm active">Standard Numbers</button>
	    	<button id="num-cn" class="options-numDisplay btn btn-primary btn-sm">Chinese Characters</button>
		</div>
		<br/><br/>
		
		<b>Language </b>
		<select id="lang-select" class="selectpicker btn btn-primary btn-sm">
	        <option value="Arabic-Male">Arabic</option>
	        <option value="Czech-Female">Czech</option>
	        <option value="Chinese-Female" selected=true>Chinese (Mandarin)</option>
	        <option value="Danish-Female">Danish</option>
	        <option value="French-Female">French</option>
	        <option value="Deutsch-Female">German</option>
	        <option value="Italian-Female">Italian</option>
	        <option value="Japanese-Female">Japanese</option>
	        <option value="Korean-Female">Korean</option>
	        <option value="Portuguese-Female">Portuguese</option>
	        <option value="Russian-Female">Russian</option>
	        <option value="Spanish-Female">Spanish</option>
	        <option value="Thai-Female">Thai</option>
	        <option value="Vietnamese-Male">Vietnamese</option>
	  	</select>
	</div>
	
	<br/>
	<p>Speech provided by <a href='http://responsivevoice.org/'>responsivevoice.org</a></p>
</div>

{% endblock %}

{% block js-foot %}
<script src="{% static 'js/responsivevoice.js' %}"></script>
<script src="{% static 'js/chineseNumbers.js' %}"></script>
{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}Registration | {{ block.super }}{% endblock %}

{% block css %}

{% endblock %}


{% block content %}

<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
    <h2>New User Registration</h2>
    <br/>
    {% crispy form %}
    </div>
    <div class="col-sm-4"></div>
</div>

{% endblock %}

{% block js-foot %}

{% endblock %}