activity_log/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'(?P<category_pk>\d+)/(?P<activity_pk>\d+)/$', views.activity_detail, name='activity_detail'),
    url(r'^play_pause_click/$', views.play_pause_click, name='play_pause_click'),
    url(r'(?P<pk>\d+)/$', views.activity_list, name='activity_list'),
    url(r'^$', views.home, name='home'),
    # url(r'^register/$', views.register, name='register'),
]

caption_maker/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'(?P<media_pk>\d+)/$', views.media_detail, name='media_detail'),
    url(r'^new$', views.create_new, name='create_new'),
    url(r'^modify/(?P<media_pk>\d+)$', views.modify_media, name='modify_media'),
    url(r'^submit_captions/$', views.submit_captions, name='submit_captions'),
    url(r'^favorite_media/$', views.favorite_media, name='favorite_media'),
    url(r'^media_list$', views.media_list, name='media_list'),
    # url(r'^login/$','django.contrib.auth.views.login', name='login',
    #     kwargs={'template_name': 'accounts/login.html'}),
    url(r'^login_register$', views.login_register, name='login_register'),
    url(r'^$', views.home, name='home'),
    # url(r'^register/$', views.register, name='register'),
]

django_sandbox/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^activity_log/', include('activity_log.urls', namespace='activity_log')),
    url(r'^caption_maker/', include('caption_maker.urls', namespace='caption_maker')),
    url(r'^admin/', admin.site.urls),
    url(r'^numbers_quiz$', views.numbers_quiz),
    url(r'nibuzhidaodeshi$', views.nibuzhidaodeshi),
    url(r'^login$', views.login_user),
    url(r'^logout$', views.logout_user),
    url(r'^registration/', views.registration),
    url(r'^$', views.home),
]

urlpatterns += staticfiles_urlpatterns()

caption_maker/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Media(models.Model):
    media_type = models.CharField(max_length = 8)
    reference_id = models.CharField(max_length = 32)
    title = models.CharField(max_length=255)
    author = models.CharField(null=True, max_length=32)
    description = models.TextField(null=True)
    start_time = models.DecimalField(null=True, max_digits=6, decimal_places=1)
    end_time = models.DecimalField(null=True, max_digits=6, decimal_places=1)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User)
    
    class Meta:
        ordering = ['title',]
    
    def __unicode__(self):
        return unicode(self.title) or u'no title'


class CaptionLine(models.Model):
    media = models.ForeignKey(Media)
    mark_time = models.DecimalField(max_digits=6, decimal_places=1)
    break_after = models.BooleanField(default=False)
    order = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['order',]
    
    def __unicode__(self):
        return unicode(self.order) + u' (' + unicode(self.mark_time) + u')' or u'no order'


class CaptionLabel(models.Model):
    label = models.CharField(max_length=32)
    order = models.IntegerField(default=1)
    created_by = models.ForeignKey(User)
    
    class Meta:
        ordering = ['label','order',]
    
    def __unicode__(self):
        return unicode(self.label) or u'no label'


class Caption(models.Model):
    caption_line = models.ForeignKey(CaptionLine)
    caption_label = models.ForeignKey(CaptionLabel, null=True)
    label = models.CharField(max_length=32) # to remove
    text = models.CharField(max_length=256)
    order = models.IntegerField(default=1)  # to remove

    class Meta:
        ordering = ['label', 'order',]
    
    def __unicode__(self):
        return unicode(self.text) or u'no caption text'


class FavoriteMedia(models.Model):
    media = models.ForeignKey(Media)
    user = models.ForeignKey(User)

caption_maker/forms.py
from django import forms
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Button
from crispy_forms.bootstrap import TabHolder, Tab, FormActions, StrictButton, InlineField

import re

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ["username", "password"]
    
    helper = FormHelper()
    helper.form_class = 'navbar-form navbar-left'
    helper.form_method = 'POST'
    helper.layout = Layout(
        InlineField('email', placeholder='Username'),
        InlineField('password', placeholder='Password'),
        StrictButton('Login', css_class='btn btn-primary navbar-sm'),
    )


# http://stackoverflow.com/questions/32416538/submit-button-not-working-in-the-modal-registration-form-in-djangof
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput(), label="Verify Password")

    helper = FormHelper()
    helper.form_tag = False
    
    # helper.layout = Layout(
    #     TabHolder(
    #         Tab(
    #             'Login',
    #             'username',
    #             'password'
    #         ),
    #         Tab(
    #             'Create Account',
    #             'username',
    #             'email',
    #             'first_name',
    #             'last_name',
    #             'password',
    #             'password2'
    #         )
    #     ),
    #     ButtonHolder(
    #         Submit('close', 'Close'),
    #         Button('submit', 'Submit')
    #     )
    # )
    # username = forms.RegexField(label="Username", max_length=30,
    #      regex=r'^[\w.@+-]+$', 
    #      error_messages = {'invalid':
    #       "This value may contain only letters, numbers and @/./+/-/_ characters."
    #      }
    # )
    # password = forms.CharField(label="Password",
    #                           widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username",  "email", "password"]
    
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError(
                  'Username can contain only alphanumeric characters')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken')
    
    
    def clean(self):
        if self.cleaned_data['password'] != self.cleaned_data['password2']:
            raise forms.ValidationError("The passwords did not match.  Please try again.")
        return self.cleaned_data

caption_maker/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

from .models import Media, Caption, CaptionLine, CaptionLabel, FavoriteMedia
from .forms import UserForm

import json, re


def login_register(request):
    if request.method=='POST':
        form = UserForm(request.POST)
    
    if form.is_valid():
        user = User.objects.create_user(username=form.cleaned_data['username'], email = form.cleaned_data['email'], password = form.cleaned_data['password'])
        user.save()
        launchers = user.get_profile()
        launchers.name = form.cleaned_data['name']
        launchers.save()
        response = {'valid': True}
    else:
        response = {'valid': False}
    
    return HttpResponse(json.dumps(response), content_type='application/json')

    
def user_login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    
    if user is not None:
        if user.is_active:
            login(request, user)
            message = ''.join(["Welcome ", user.first_name, "!"])
        else:
            message = "Username not found, please try again!"
    
    else:
        message = "Invalid login credentials, please try again!"
    
    response = {
        'message': message
    }
    
    return HttpResponse(json.dumps(response), content_type='application/json')


def home(request):
    response = {}
    return render(request, 'caption_maker/home.html', response)


def create_new(request):
    response = {
        'action': 'new'
    }
    
    return render(request,  'caption_maker/create_new.html', response)


def favorite_media(request):
    data = request.POST
    
    try:
        favorite = FavoriteMedia.objects.get(media_id = data['media_id'], user_id = request.user)
        favorite.delete()
    except FavoriteMedia.DoesNotExist:
        favorite = FavoriteMedia(media_id = data['media_id'], user= request.user)
        favorite.save()
    
    response = {
        'hello': 'hello'
    }
    
    return HttpResponse(json.dumps(response), content_type='application/json')


def modify_media(request, media_pk):
    media = get_object_or_404(Media, pk=media_pk)
    captionLines = CaptionLine.objects.filter(media_id=media_pk)
    labelArr = [];
    captionArr = [];
    timeList = [];
    
    for idx1, capLine in enumerate(captionLines):
        timeList.append(float(capLine.mark_time));
        for idx2, cap in enumerate(capLine.caption_set.all()):
            if(idx1 == 0):
                # Create new list to hold captions grouped by label (eg: English)
                captionArr.append([])
                labelArr.append(cap.label)

            # Append caption into appropriate caption list
            captionArr[idx2].append(cap)
            if capLine.break_after:
                captionArr[idx2].append("")
    
    response = {
        'action': 'modify',
        'media': media,
        'labels': labelArr,
        'caption_lines': captionLines,
        'captions': captionArr,
        'timeList': timeList
    }
    
    return render(request, 'caption_maker/create_new.html', response)


def media_list(request):
    media_list = Media.objects.all()
    
    if request.user.is_authenticated():
        favorite_media_ids = FavoriteMedia.objects.filter(user=request.user).values_list('media_id', flat=True)
    else:
        favorite_media_ids = []
    
    response = {
        'media_list': media_list,
        'favorite_media_ids': favorite_media_ids
    }
    
    return render(request, 'caption_maker/media_list.html', response)


def submit_captions(request):
    if request.method == 'POST':
        data = request.POST
        
        if data['start_time']:
            start_time = data['start_time']
        else:
            start_time = None
        
        if data['end_time']:
            end_time = data['end_time']
        else:
            end_time = None
        
        if data['action'] == "new":
            media = Media(media_type=data['mediaType'], reference_id=data['refId'], title=data[
                          'title'], author=data['author'], description=data['description'],
                          start_time=start_time, end_time=end_time, created_by=request.user)
        else:
            media = get_object_or_404(Media, pk=data['media_pk'])
            media.title = data['title']
            media.author = data['author']
            media.description = data['description']
            
            CaptionLine.objects.filter(media_id=data['media_pk']).delete()
        
        media.save()
        
        capList = re.findall(r'\{([^}]*)\}', data['captions'])
        capLines = json.loads(data['captionLines'])
        
        capLabelDict = {};

        for idx1, cap in enumerate(capList):
            c = json.loads("{" + cap + "}")
            
            captionLine = CaptionLine(media=media, mark_time=c['time'],  order=c[
                                      'order'], break_after=c['break_after'])
            captionLine.save()

            for idx2, key in enumerate(capLines):
                
                captionLabel = None
                
                if idx1 == 0:
                    print "label %s, order %s, created_by %s" % (key, idx2, request.user)
                    captionLabel = CaptionLabel(label=key, order=idx2, created_by=request.user)
                    captionLabel.save()
                    capLabelDict[idx2] = captionLabel
                else:
                    captionLabel = capLabelDict[idx2]
                
                caption = Caption(caption_line=captionLine, caption_label=captionLabel,
                                  order=idx2, label=key, text=capLines[key][idx1])
                caption.save()
        
        response = {
            'url': '/caption_maker/' + str(media.id)
        }
    return HttpResponse(json.dumps(response), content_type='application/json')


def media_detail(request, media_pk):
    if request.method == 'GET':
        media = get_object_or_404(Media, pk=media_pk)
        captionLines = CaptionLine.objects.filter(media_id=media_pk)
        timeList = []
    
        for capLine in captionLines:
            timeList.append(float(capLine.mark_time))
    
        labelList = list(Caption.objects.filter(caption_line__in=captionLines).values_list('label', flat=True).distinct())
        #print(labelList)
        response = {
            'media': media,
            'captionLines': captionLines,
            'timeList': timeList,
            'labelList': json.dumps(labelList)
        }
    
    return render(request, 'caption_maker/media_detail.html', response)

caption_maker/templates/caption_maker/login_register.html
{% load crispy_forms_tags %}


<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Account Management</h4>
      </div>
      
      <div class="modal-body">
        <form action="{% url 'caption_maker:login_register' %}" method="post">{% csrf_token %}
            {% crispy user_form %}
            <hr/>
           
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                <input type="submit" name="submit_feedback" value="Submit" class="btn btn-primary" id="submit-id-submit_feedback" />
           
        </form>
      </div>
      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

caption_maker/templates/caption_maker/media_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Captioned Videos{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'caption_maker/css/media_detail.css' %}">
<script>
  var videoId = "{{ media.reference_id }}";
  var timeArr = {{ timeList|safe }};
  var startTime = "{{ media.start_time }}";
  startTime = (startTime == "None") ? null : Math.floor(Number(startTime));
  var endTime = "{{ media.end_time }}"
  endTime = (endTime == "None") ? null : Math.ceil(Number(endTime));
  var labelList = {{ labelList|safe }};
</script>
{% endblock %}

{% block content %}
<div class="text-center row">
  <div class=".col-md-12">
    <h3 id="title">{{ media.title }}</h3>
    <h4>{{ media.author }}</h4>
    <div id="player" class="video"></div>

    <div class="lyrics-container center">
      <table class="lyrics center">
        <tbody>
          <!-- for every line -->
          {% for capLine in captionLines %}
          <!-- for every caption set (Chinese, English, etc) (there may be 
                multiple caption sets per line.  Order determined by meta setting) -->
          {% for cap in capLine.caption_set.all %}
          <tr class="{{ cap.label|lower }} caption-cell line-{{ capLine.order }}">
            <td>
              <!-- display caption text -->
              {{ cap.text }}
            </td>
          </tr>
          {% endfor %}

          {% if capLine.break_after %}
          <tr><td> &nbsp; </td></tr>
          {% endif %}

          {% endfor %}

        </tbody>
      </table>
    </div>
    
    <div id="caption-toggle">
      <b>Show / Hide Captions: </b>
	    <div id="toggle-buttons" class="btn-group"></div>
    </div>
    
  </div>
</div>
{% endblock %}

{% block js-foot %}
<script src="{% static 'caption_maker/js/player.js' %}"></script>
<script src="{% static 'caption_maker/js/media_detail.js' %}"></script>
{% endblock %}

caption_maker/templates/caption_maker/media_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Captioned Videos | {{ block.super }}{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'caption_maker/css/media_list.css' %}">
<script>
  var user_id = {{ user.id }};
  var media_ids = {{ favorite_media_ids|safe }};
</script>
{% endblock %}

{% block content %}

<h2>Summary</h2>
<p>
  Listening to songs are a great way to study a foreign language.  I've been able to find many songs on YouTube, 
  but most of them do not have captions to help me follow along.  Normally the original uploader can only add 
  captions to a video, but with this app you can add captions to any video you want and see the captions that 
  other users have added to videos!  Please feel free to try this out and send any questions, comments, or 
  suggestions to 
  <a href="mailto:theodore.lano@gmail.com?Subject=Caption%20Maker%20Comment" target="_top">
    theodore.lano@gmail.com
  </a>
</p>
<p>
  <strong>Additional Features in Development:</strong><br/>
  <ul>
    <li>Tag Media for quick finding and sorting (eg: Mandarin, Spanish, etc)</li>
    <li>Prevent users from changing other people's captions</li>
    <li>Type-ahead for labels when creating new captions</li>
  </ul>
</p>

<br/>
<div class="media-list-header">
  <h2>Captioned Media</h2>
  <br/>
  <a href="{% url 'caption_maker:create_new' %}" class="btn btn-success pull-right {% if not user.is_authenticated %}disabled{% endif %}">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create Your Own!
      {% if not user.is_authenticated %}
        (Requires Login)
      {% endif %}
  </a>
</div>
<br/>

<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#all-media">All Media</a></li>
  {% if user.is_authenticated %}
  <li><a data-toggle="tab" href="#favorite-media">Favorites</a></li>
  {% endif %}
</ul>

<div class="tab-content">
  <div id="all-media" class="tab-pane fade in active">
    <table class="table table-striped">
      <thead>
        <tr>
          <td class="id-col hidden"></td>
          {% if user.is_authenticated %}
          <td class="favorite-col"></td> <!--favorite star icon-->
          {% endif %}
          <td>Title</td>
          <td>Author</td>
          <td>Description</td>
          {% if user.is_authenticated %}
          <td></td><!--Modify Button-->
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for media in media_list %}
        <tr>
          <td class="id-col hidden">
            {{ media.id }}
          </td>
          {% if user.is_authenticated %}
          <td class="favorite-col favorite">
            <span class="glyphicon 
            {% if media.id in favorite_media_ids %} glyphicon-star star-color
            {% else %} glyphicon-star-empty
            {% endif %}" aria-hidden="true"></span>
          </td>
          {% endif %}
          <td>
            <a href="{% url 'caption_maker:media_detail' media_pk=media.pk %}">
              {{ media.title }}
            </a>
          </td>
          <td>
            {{ media.author }}
          </td>
          <td>
            {{ media.description }}
          </td>
          {% if user.is_authenticated %}
          <td>
          	<a href="{% url 'caption_maker:modify_media' media_pk=media.pk %}">
        			<button type="button" class="btn btn-primary caption-modify">
          			<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Modify
        			</button>
      			</a>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% if user.is_authenticated %}
  <div id="favorite-media" class="tab-pane fade">
    {% if not favorite_media_ids %}
      <br/><br/>
      <h3 class="text-center">No favorites selected!</h3>
      <h1 class="text-center">:'(</h1>
    {% else %}
    
    <table class="table table-striped">
      <thead>
        <tr>
          <td class="id-col hidden"></td>
          {% if user.is_authenticated %}
          <td class="favorite-col"></td> <!--favorite star icon-->
          {% endif %}
          <td>Title</td>
          <td>Author</td>
          <td>Description</td>
          {% if user.is_authenticated %}
          <td></td><!--Modify Button-->
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for media in media_list %}
        {% if media.id in favorite_media_ids %}
        <tr>
          <td class="id-col hidden">
            {{ media.id }}
          </td>
          <td class="favorite-col favorite">
            <span class="glyphicon glyphicon-star star-color" aria-hidden="true"></span>
          </td>
          <td>
            <a href="{% url 'caption_maker:media_detail' media_pk=media.pk %}">
              {{ media.title }}
            </a>
          </td>
          <td>
            {{ media.author }}
          </td>
          <td>
            {{ media.description }}
          </td>
          {% if user.is_authenticated %}
          <td>
          	<a href="{% url 'caption_maker:modify_media' media_pk=media.pk %}">
        			<button type="button" class="btn btn-primary caption-modify">
          			<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Modify
        			</button>
      			</a>
          </td>
          {% endif %}
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
  </div>
  {% endif %}
</div>


{% endblock %}

{% block js-foot %}
<script src="{% static 'caption_maker/js/media_list.js' %}"></script>
{% endblock %}

caption_maker/templates/caption_maker/media_list_tablebody.html
<tbody>
{% for media in media_list %}
<tr>
  <td class="id-col hidden">
    {{ media.id }}
  </td>
  {% if user.is_authenticated %}
  <td class="favorite-col favorite">
    <span class="glyphicon 
    {% if media.id in favorite_media_ids %} glyphicon-star star-color
    {% else %} glyphicon-star-empty
    {% endif %}" aria-hidden="true"></span>
  </td>
  {% endif %}
  <td>
    <a href="{% url 'caption_maker:media_detail' media_pk=media.pk %}">
      {{ media.title }}
    </a>
  </td>
  <td>
    {{ media.author }}
  </td>
  <td>
    {{ media.description }}
  </td>
  {% if user.is_authenticated %}
  <td>
  	<a href="{% url 'caption_maker:modify_media' media_pk=media.pk %}">
			<button type="button" class="btn btn-primary caption-modify">
  			<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Modify
			</button>
  		</a>
  </td>
  {% endif %}
</tr>
{% endfor %}
</tbody>